<a href="https://colab.research.google.com/github/wankhadearpit21-pixel/Python-Project/blob/main/Dataset2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()

Saving employee_dataset_194x64.csv to employee_dataset_194x64.csv

In [3]:
filepath="/content/employee_dataset_194x64.csv"
df=pd.read_csv(filepath)
df

,EmployeeID,FirstName,LastName,Department,City,JobRole,Grade,Status,Age,YearsExperience,...,Metric39,Metric40,Metric41,Metric42,Metric43,Metric44,Metric45,Metric46,Metric47,Metric48
0,EMP1000,Rohan,Nair,Marketing,Solapur,Lead,E,Probation,22,33,...,30,81,87,47,30,10,61,14,17,43
1,EMP1001,Nikita,Bansal,Admin,Nashik,Specialist,B,Inactive,55,28,...,41,91,10,39,31,28,67,96,96,73
2,EMP1002,Manoj,Patil,Admin,Solapur,Analyst,A,Probation,54,3,...,67,22,58,5,31,59,90,40,88,54
3,EMP1003,Suresh,Bhosale,Marketing,Nanded,Executive,A,Active,50,16,...,60,77,85,37,98,66,91,89,55,18
4,EMP1004,Anjali,Gupta,R&D,Mumbai,Specialist,D,Active,33,34,...,60,93,14,40,52,64,42,79,30,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,EMP1189,Suresh,Joshi,R&D,Kolhapur,Consultant,B,Active,52,5,...,32,78,30,57,25,32,94,43,48,86
190,EMP1190,Isha,Pillai,Legal,Thane,Coordinator,E,Probation,31,16,...,29,12,51,30,40,9,18,26,16,97
191,EMP1191,Isha,Kapoor,Admin,Amravati,Officer,C,Active,43,24,...,58,65,87,90,98,79,2,98,55,74
192,EMP1192,Amit,Rao,Support,Kolhapur,Lead,A,Inactive,46,27,...,75,18,97,11,37,63,35,25,44,33
193,EMP1193,Karan,Bhosale,Operations,Aurangabad,Lead,C,Probation,54,1,...,14,23,22,45,87,63,42,59,29,32

In [4]:
df.head()

,EmployeeID,FirstName,LastName,Department,City,JobRole,Grade,Status,Age,YearsExperience,...,Metric39,Metric40,Metric41,Metric42,Metric43,Metric44,Metric45,Metric46,Metric47,Metric48
0,EMP1000,Rohan,Nair,Marketing,Solapur,Lead,E,Probation,22,33,...,30,81,87,47,30,10,61,14,17,43
1,EMP1001,Nikita,Bansal,Admin,Nashik,Specialist,B,Inactive,55,28,...,41,91,10,39,31,28,67,96,96,73
2,EMP1002,Manoj,Patil,Admin,Solapur,Analyst,A,Probation,54,3,...,67,22,58,5,31,59,90,40,88,54
3,EMP1003,Suresh,Bhosale,Marketing,Nanded,Executive,A,Active,50,16,...,60,77,85,37,98,66,91,89,55,18
4,EMP1004,Anjali,Gupta,R&D,Mumbai,Specialist,D,Active,33,34,...,60,93,14,40,52,64,42,79,30,28

In [5]:
df.tail()

,EmployeeID,FirstName,LastName,Department,City,JobRole,Grade,Status,Age,YearsExperience,...,Metric39,Metric40,Metric41,Metric42,Metric43,Metric44,Metric45,Metric46,Metric47,Metric48
189,EMP1189,Suresh,Joshi,R&D,Kolhapur,Consultant,B,Active,52,5,...,32,78,30,57,25,32,94,43,48,86
190,EMP1190,Isha,Pillai,Legal,Thane,Coordinator,E,Probation,31,16,...,29,12,51,30,40,9,18,26,16,97
191,EMP1191,Isha,Kapoor,Admin,Amravati,Officer,C,Active,43,24,...,58,65,87,90,98,79,2,98,55,74
192,EMP1192,Amit,Rao,Support,Kolhapur,Lead,A,Inactive,46,27,...,75,18,97,11,37,63,35,25,44,33
193,EMP1193,Karan,Bhosale,Operations,Aurangabad,Lead,C,Probation,54,1,...,14,23,22,45,87,63,42,59,29,32

In [6]:
df.shape

(194, 64)

In [7]:
df.columns

Index(['EmployeeID', 'FirstName', 'LastName', 'Department', 'City', 'JobRole',
       'Grade', 'Status', 'Age', 'YearsExperience', 'Salary', 'Bonus',
       'ProjectsCompleted', 'LeavesTaken', 'PerformanceScore', 'TrainingHours',
       'Metric01', 'Metric02', 'Metric03', 'Metric04', 'Metric05', 'Metric06',
       'Metric07', 'Metric08', 'Metric09', 'Metric10', 'Metric11', 'Metric12',
       'Metric13', 'Metric14', 'Metric15', 'Metric16', 'Metric17', 'Metric18',
       'Metric19', 'Metric20', 'Metric21', 'Metric22', 'Metric23', 'Metric24',
       'Metric25', 'Metric26', 'Metric27', 'Metric28', 'Metric29', 'Metric30',
       'Metric31', 'Metric32', 'Metric33', 'Metric34', 'Metric35', 'Metric36',
       'Metric37', 'Metric38', 'Metric39', 'Metric40', 'Metric41', 'Metric42',
       'Metric43', 'Metric44', 'Metric45', 'Metric46', 'Metric47', 'Metric48'],
      dtype='object')

In [8]:
df.info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         194 non-null    object
 1   FirstName          194 non-null    object
 2   LastName           194 non-null    object
 3   Department         194 non-null    object
 4   City               194 non-null    object
 5   JobRole            194 non-null    object
 6   Grade              194 non-null    object
 7   Status             194 non-null    object
 8   Age                194 non-null    int64
 9   YearsExperience    194 non-null    int64
 10  Salary             194 non-null    int64
 11  Bonus              194 non-null    int64
 12  ProjectsCompleted  194 non-null    int64
 13  LeavesTaken        194 non-null    int64
 14  PerformanceScore   194 non-null    int64
 15  TrainingHours      194 non-null    int64
 16  Metric01           194 non-null    int64
 17  Metric02           194 non-null    int64
 18  Metric03           194 non-null    int64
 19  Metric04           194 non-null    int64
 20  Metric05           194 non-null    int64
 21  Metric06           194 non-null    int64
 22  Metric07           194 non-null    int64
 23  Metric08           194 non-null    int64
 24  Metric09           194 non-null    int64
 25  Metric10           194 non-null    int64
 26  Metric11           194 non-null    int64
 27  Metric12           194 non-null    int64
 28  Metric13           194 non-null    int64
 29  Metric14           194 non-null    int64
 30  Metric15           194 non-null    int64
 31  Metric16           194 non-null    int64
 32  Metric17           194 non-null    int64
 33  Metric18           194 non-null    int64
 34  Metric19           194 non-null    int64
 35  Metric20           194 non-null    int64
 36  Metric21           194 non-null    int64
 37  Metric22           194 non-null    int64
 38  Metric23           194 non-null    int64
 39  Metric24           194 non-null    int64
 40  Metric25           194 non-null    int64
 41  Metric26           194 non-null    int64
 42  Metric27           194 non-null    int64
 43  Metric28           194 non-null    int64
 44  Metric29           194 non-null    int64
 45  Metric30           194 non-null    int64
 46  Metric31           194 non-null    int64
 47  Metric32           194 non-null    int64
 48  Metric33           194 non-null    int64
 49  Metric34           194 non-null    int64
 50  Metric35           194 non-null    int64
 51  Metric36           194 non-null    int64
 52  Metric37           194 non-null    int64
 53  Metric38           194 non-null    int64
 54  Metric39           194 non-null    int64
 55  Metric40           194 non-null    int64
 56  Metric41           194 non-null    int64
 57  Metric42           194 non-null    int64
 58  Metric43           194 non-null    int64
 59  Metric44           194 non-null    int64
 60  Metric45           194 non-null    int64
 61  Metric46           194 non-null    int64
 62  Metric47           194 non-null    int64
 63  Metric48           194 non-null    int64
dtypes: int64(56), object(8)
memory usage: 97.1+ KB

In [9]:
df.dtypes

EmployeeID    object
FirstName     object
LastName      object
Department    object
City          object
               ...
Metric44       int64
Metric45       int64
Metric46       int64
Metric47       int64
Metric48       int64
Length: 64, dtype: object

In [10]:
df.isnull().sum()

EmployeeID    0
FirstName     0
LastName      0
Department    0
City          0
             ..
Metric44      0
Metric45      0
Metric46      0
Metric47      0
Metric48      0
Length: 64, dtype: int64

In [11]:
df.nunique()

EmployeeID    194
FirstName      20
LastName       20
Department     10
City           10
             ...
Metric44       87
Metric45       88
Metric46       84
Metric47       89
Metric48       84
Length: 64, dtype: int64

In [12]:
df.sample(5)

,EmployeeID,FirstName,LastName,Department,City,JobRole,Grade,Status,Age,YearsExperience,...,Metric39,Metric40,Metric41,Metric42,Metric43,Metric44,Metric45,Metric46,Metric47,Metric48
118,EMP1118,Arjun,Kulkarni,IT,Nashik,Lead,B,Active,33,19,...,7,24,50,47,54,1,48,49,14,31
59,EMP1059,Divya,Kulkarni,Finance,Nanded,Lead,A,On Leave,55,8,...,73,56,89,28,60,62,88,7,41,63
169,EMP1169,Sanjay,Joshi,Marketing,Aurangabad,Consultant,D,Active,32,5,...,61,73,40,79,32,36,0,27,13,67
174,EMP1174,Vikram,Pillai,Marketing,Nanded,Coordinator,B,Probation,42,14,...,95,22,37,87,3,54,99,86,5,38
35,EMP1035,Kavya,Patil,Marketing,Amravati,Executive,A,On Leave,32,17,...,65,56,9,59,25,87,82,26,0,82

In [13]:
df.value_counts()

EmployeeID  FirstName  LastName  Department  City        JobRole      Grade  Status     Age  YearsExperience  Salary  Bonus  ProjectsCompleted  LeavesTaken  PerformanceScore  TrainingHours  Metric01  Metric02  Metric03  Metric04  Metric05  Metric06  Metric07  Metric08  Metric09  Metric10  Metric11  Metric12  Metric13  Metric14  Metric15  Metric16  Metric17  Metric18  Metric19  Metric20  Metric21  Metric22  Metric23  Metric24  Metric25  Metric26  Metric27  Metric28  Metric29  Metric30  Metric31  Metric32  Metric33  Metric34  Metric35  Metric36  Metric37  Metric38  Metric39  Metric40  Metric41  Metric42  Metric43  Metric44  Metric45  Metric46  Metric47  Metric48
EMP1000     Rohan      Nair      Marketing   Solapur     Lead         E      Probation  22   33               89674   4806   1                  20           3                 159            33        39        29        18        16        10        4         77        33        63        78        83        58        14        58        69        79        10        91        20        5         55        60        78        43        21        80        76        84        64        29        45        96        71        11        51        99        71        30        81        87        47        30        10        61        14        17        43          1
EMP1001     Nikita     Bansal    Admin       Nashik      Specialist   B      Inactive   55   28               149132  2190   26                 27           65                147            25        75        59        62        57        76        20        55        39        60        3         54        75        34        79        62        60        91        28        89        23        12        13        76        52        3         38        51        89        68        7         85        54        62        6         47        87        60        41        91        10        39        31        28        67        96        96        73          1
EMP1002     Manoj      Patil     Admin       Solapur     Analyst      A      Probation  54   3                144044  9108   8                  10           4                 142            4         53        97        37        86        52        77        66        74        28        95        15        48        75        91        35        99        53        78        39        17        55        51        22        9         48        35        65        25        50        97        86        0         46        54        42        75        32        67        22        58        5         31        59        90        40        88        54          1
EMP1003     Suresh     Bhosale   Marketing   Nanded      Executive    A      Active     50   16               133542  12178  0                  22           99                175            98        75        31        66        89        71        3         15        60        38        22        45        58        52        15        1         55        86        34        44        86        17        95        80        86        58        39        51        71        21        56        29        69        25        61        38        42        65        60        77        85        37        98        66        91        89        55        18          1
EMP1004     Anjali     Gupta     R&D         Mumbai      Specialist   D      Active     33   34               38760   2875   10                 1            96                198            60        45        66        58        28        67        22        82        49        87        69        61        30        43        61        21        88        44        5         76        5         53        5         47        51        72        44        91        4         87        72        68        44        56        89        48        22        29        60        93        14        40        52        64        42        79        30        28          1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
EMP1189     Suresh     Joshi     R&D         Kolhapur    Consultant   B      Active     52   5                140142  19169  28                 15           91                130            64        35        80        69        25        70        1         62        92        6         28        77        4         13        26        35        3         70        5         26        61        30        99        50        89        16        16        2         54        43        39        60        4         55        46        56        80        73        32        78        30        57        25        32        94        43        48        86          1
EMP1190     Isha       Pillai    Legal       Thane       Coordinator  E      Probation  31   16               116736  16163  32                 7            7                 96             7         98        80        55        24        46        21        96        47        21        39        31        66        36        54        44        74        28        90        9         79        81        39        17        48        68        35        73        88        21        2         37        96        96        5         97        63        97        29        12        51        30        40        9         18        26        16        97          1
EMP1191     Isha       Kapoor    Admin       Amravati    Officer      C      Active     43   24               76924   5782   9                  0            70                195            44        44        96        75        9         70        56        68        76        73        89        98        57        78        28        35        95        2         8         33        33        42        65        87        61        38        98        4         79        52        75        2         48        57        15        73        89        25        58        65        87        90        98        79        2         98        55        74          1
EMP1192     Amit       Rao       Support     Kolhapur    Lead         A      Inactive   46   27               28726   18792  49                 11           15                24             86        72        95        50        44        25        71        42        47        52        29        9         26        67        19        21        48        82        56        35        86        6         72        71        37        81        80        89        57        58        75        83        97        92        71        73        85        29        75        18        97        11        37        63        35        25        44        33          1
EMP1193     Karan      Bhosale   Operations  Aurangabad  Lead         C      Probation  54   1                114152  16724  39                 4            82                147            46        52        71        36        82        39        6         47        48        78        80        2         79        39        24        77        6         9         30        24        87        0         86        29        22        70        1         60        82        93        65        69        29        63        17        69        61        72        14        23        22        45        87        63        42        59        29        32          1
Name: count, Length: 194, dtype: int64